// Per-clock-domain functional-reset conditioner.
//
// The asynchronous request is captured by a conventional two-flop chain whose
// assertion is asynchronous and whose release is synchronized.  That chain is
// intentionally not the functional reset output: reset_out is generated by a
// second, fully synchronous release pipe.  Consequently every transition of
// reset_out occurs on a rising edge of clk and downstream BRAM address/control
// logic is never driven by a register with an asynchronous set/reset.

module reset_sync #(
    parameter integer RELEASE_STAGES = 4
) (
    input logic clk,
    input logic reset_async,
    output logic reset_out
);

    localparam integer REQUEST_SYNC_STAGES = 2;

    // Only this request synchronizer has an asynchronous control. It must not
    // directly drive functional logic outside this module.
    (* ASYNC_REG = "TRUE", SHREG_EXTRACT = "NO" *)
    logic [REQUEST_SYNC_STAGES-1:0] request_sync_q;

    (* SHREG_EXTRACT = "NO" *)
    logic [RELEASE_STAGES-1:0] release_pipe_q;

    initial begin
        // 7-series configuration implements these as flip-flop INIT values,
        // keeping reset asserted before the first generated-clock edge.
        request_sync_q = '1;
        release_pipe_q = '1;

        assert (RELEASE_STAGES >= 4)
            else $fatal(1, "reset_sync RELEASE_STAGES must be at least 4");
    end

    assign reset_out = release_pipe_q[RELEASE_STAGES-1];

    always_ff @(posedge clk or posedge reset_async) begin
        if (reset_async) begin
            request_sync_q <= '1;
        end else begin
            request_sync_q <= request_sync_q << 1;
        end
    end

    always_ff @(posedge clk) begin
        if (request_sync_q[REQUEST_SYNC_STAGES-1]) begin
            release_pipe_q <= '1;
        end else begin
            release_pipe_q <= release_pipe_q << 1;
        end
    end

endmodule
